options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the microservice
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install', '-DskipTests']
    dir: '.'

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cloudcomputing-cw-bda/cloud-computing/patient-health-record:latest', '.']

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cloudcomputing-cw-bda/cloud-computing/patient-health-record:latest']

  # Step 4: Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - '--namespace=health-app'
      - 'deployment/patient'
      - 'patient=us-central1-docker.pkg.dev/cloudcomputing-cw-bda/cloud-computing/patient-health-record:latest'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-east1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-computing-cw'
    dir: '.'